version: "3.7"

services:
  db:
    container_name: sip_db_dev
    image: postgres
    networks:
      - sip
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PWD}
      PG_DATA: /var/lib/postgresql/data
      POSTGRES_INITDB_ARGS: --auth-host=scram-sha-256  
    ports:
      - ${EXT_PORT}:${INT_PORT}
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}

#### READ THIS!
# Docker custom-network works as follows:
#     1. Everytime 'docker-compose up' is issued, docker creates
#       a network using the DIRECTORY_NAME where the docker-compose.yml 
#       file is located as network name.
#       As the current structure is:
#         - sip_dev
#           |_docker-compose.yml
#     
#       The network name of this container will be 'sip_db_dev' with an
#       '_' (underscore) appended as separator for every attached 
#       container.
#   
#     2. After network creation, every container defined in this 
#       file will join to the network 'sip_dev' using the specified
#       network name. 
#           (Of course, that network must be listed as below for docker
#           to recognize it)
#       As the current name of the network is 'sip', the resulting
#       network will be: 'sip_sip_dev'
#     3. Check the output of 'docker network ls' to be sure.

networks:
  sip:

# For more info about docker networking visit: https://docs.docker.com/compose/networking/
