version: "3.7"

services:
  db:
    container_name: sip_db_prod
    image: postgres
    networks:
      - sip
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PWD}
      PG_DATA: /var/lib/postgresql/data
      POSTGRES_INITDB_ARGS: --auth-host=scram-sha-256  
    ports:
      - ${EXT_PORT}:${INT_PORT}
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}

networks:
  sip:

# For more info about docker networking visit: https://docs.docker.com/compose/networking/
